import React from 'react';
import ReactDOM from 'react-dom/client';
import './styles/App.css'; // General app styles, can be minimal
// Tailwind CSS is imported via the link tag in public/index.html, generated by the build process.
// If you have a main CSS file that imports Tailwind, you can import it here instead.
import App from './App';
import reportWebVitals from './reportWebVitals';

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals(); 