name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_backend:
    name: Test Backend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11'] # Example: test on multiple Python versions

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install backend dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run backend tests
      working-directory: ./backend
      run: |
        # Ensure PYTHONPATH is set if tests import from app.* and run from backend/
        # This is often needed if your tests are in a subfolder like backend/tests
        # and your app code is in backend/app
        export PYTHONPATH=$(pwd) 
        python -m pytest -v

  test_file_watcher:
    name: Test File Watcher
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install file_watcher dependencies
      working-directory: ./file_watcher
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run file_watcher tests
      working-directory: ./file_watcher
      run: |
        # Assuming tests are in the root of file_watcher/ or a tests/ subfolder
        # and imports are relative or PYTHONPATH is handled by pytest structure itself.
        # If watcher.py imports modules from the root of the project, PYTHONPATH might need adjustment.
        # For now, we assume standard pytest discovery from this directory.
        pytest test_watcher.py

  # We will add the file_watcher test job next 